name: Build and Deploy Next.js

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Verify Secrets Presence
        run: |
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then echo "FTP_SERVER is not set"; else echo "FTP_SERVER is set"; fi
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then echo "FTP_USERNAME is not set"; else echo "FTP_USERNAME is set"; fi
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then echo "FTP_PASSWORD is not set"; else echo "FTP_PASSWORD is set"; fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npx next build

      - name: Upload built files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: './out/'
          server-dir: '~./public_html/out/'
